repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
        exclude: ^docs/build/
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^src/staticfiles/
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      exclude: migrations/
-   repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
    -   id: isort
        exclude: ^migrations/
