FROM ubuntu:18.04

MAINTAINER Daniel Vagg "https://github.com/vadix-solutions/portunus-lite"

RUN apt-get update && \
	apt-get install -y \
		python3 python3-virtualenv \
		python3-pip libxml2-dev libxslt1-dev \
		libsasl2-dev python3-dev libldap2-dev libssl-dev libkrb5-dev \
        libpq-dev git \
        curl wget vim

WORKDIR /opt/vdx_id_agent

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# Installing Oracle instant client
WORKDIR    /opt/oracle
RUN        apt-get update && apt-get install -y libaio1 wget unzip \
            && wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip \
            && unzip instantclient-basiclite-linuxx64.zip \
            && rm -f instantclient-basiclite-linuxx64.zip \
            && cd /opt/oracle/instantclient* \
            && rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci \
            && echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf \
            && ldconfig

COPY vdx_id_agent/requirements.txt /opt/vdx_id_agent/requirements.txt
RUN pip3 install -r /opt/vdx_id_agent/requirements.txt

RUN mkdir -p /data/agent_keys

COPY vdx_id_agent /opt/vdx_id_agent

WORKDIR /opt
CMD ["bash", "vdx_id_agent/celery_agent.sh"]
