version: 2.1
jobs:
  'Unit Testing':
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.13
      - run:
          name: Build Unit Test Environment
          command: |
            docker-compose -f docker-compose.test.yml build
            mkdir cov_report
            chmod 777 cov_report
            ls -al ./redis_tls/tests/tls
      - run:
          name: Start Unit Test Environment
          command: |
            docker-compose -f docker-compose.test.yml up -d
            docker-compose -f docker-compose.test.yml ps
            docker-compose logs redis_int
      - run:
          name: Migrate DB
          command: |
            docker-compose -f docker-compose.test.yml exec django_wsgi python3 manage.py migrate
      - run:
          name: Initialising Test Environment
          command: |
            docker-compose -f docker-compose.test.yml exec django_wsgi python3 manage.py loaddata init_data
            docker-compose -f docker-compose.test.yml exec django_wsgi python3 manage.py collectstatic --no-input
      - run:
          name: Execute Unit Tests
          command: |
            docker-compose -f docker-compose.test.yml exec django_wsgi pytest --cov-report html:cov_report --cov-report xml:cov_report/report.xml--cov=. --create-db
      - store_artifacts:
          path: cov_report
workflows:
  version: 2.1
  'Test, Build and Deploy':
    jobs:
      - 'Unit Testing'
