# Generated by Django 2.2.13 on 2022-03-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
        ('id_infra', '0001_initial'),
        ('vdx_id', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viaccessdomain',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_access_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viaccessdomain',
            name='rotate_password_policy',
            field=models.ForeignKey(blank=True, help_text='The Vault password policy to use for this object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vdx_id.VaultPasswordPolicy'),
        ),
        migrations.AddField(
            model_name='hostscandefinition',
            name='access_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_definitions', to='id_infra.ViAccessDomain'),
        ),
        migrations.AddField(
            model_name='hostscandefinition',
            name='scanning_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_definitions', to='id_infra.ViAgent'),
        ),
        migrations.AddField(
            model_name='historicalviaccessdomain',
            name='group_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='historicalviaccessdomain',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalviaccessdomain',
            name='interface',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='id_infra.ViAgentInterface'),
        ),
        migrations.AddField(
            model_name='historicalviaccessdomain',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalviaccessdomain',
            name='rotate_password_policy',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The Vault password policy to use for this object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vdx_id.VaultPasswordPolicy'),
        ),
        migrations.AddField(
            model_name='agentcelerytask',
            name='source_api_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='id_infra.AgentApiTask'),
        ),
        migrations.AddField(
            model_name='agentapitask',
            name='access_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='id_infra.ViAccessDomain'),
        ),
        migrations.AddField(
            model_name='agentapitask',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='accesshost',
            name='access_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='id_infra.ViAccessDomain'),
        ),
        migrations.AddField(
            model_name='accesshost',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='id_infra.ViAgent'),
        ),
        migrations.AddField(
            model_name='accesshost',
            name='source_scan_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='id_infra.HostScanDefinition'),
        ),
    ]
