# Generated by Django 2.2.13 on 2022-03-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_infra', '0002_auto_20220318_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalviaccessdomain',
            name='circuit_break_config',
        ),
        migrations.RemoveField(
            model_name='historicalviaccessdomain',
            name='circuit_break_records',
        ),
        migrations.RemoveField(
            model_name='viaccessdomain',
            name='circuit_break_config',
        ),
        migrations.RemoveField(
            model_name='viaccessdomain',
            name='circuit_break_records',
        ),
    ]
